IDs:
  controls:
    comparators: trendsComparator
    populations: trendsPopulations
    ages: trendsAges
    outcomes: trendsOutcomes
    interventions: trendsInterventions
    analyses: trendsAnalyses
    colorblind: trendsColorblind
  downloads:
    png: trendsPNG
    pdf: trendsPDF
    pptx: trendsPPTX
    csv: trendsCSV
    xlsx: trendsXLSX
  panels:
    control: trendsControlPanel
    visualization: trendsVisualizationPanel
  title: trendsTitle
  subtitle: trendsSubtitle
  plot: trendsPlot
comparators:
  heading: Comparator
  values:
  - absolute_value
  - pct_basecase_same_year
  - pct_basecase_2016
  labels:
    absolute_value: Absolute values
    pct_basecase_same_year: Percentage of base case value in the same year
    pct_basecase_2016: Percentage of base case value in 2016
  formatted:
    absolute_value: ''
    pct_basecase_same_year: Percentage of base case value in the same year
    pct_basecase_2016: Percentage of base case value in 2016
  selected:
  - yes
  - no
  - no
populations:
  heading: Population
  values:
  - all_populations
  - usb_population
  - fb_population
  labels:
    all_populations: Total
    usb_population: US-born
    fb_population: Foreign-born
  selected:
  - yes
  - no
  - no
  formatted:
    all_populations: total US population
    usb_population: US-born population
    fb_population: foreign-born US population
ages:
  heading: Age groups
  values:
  - all_ages
  - age_0_24
  - age_25_64
  - age_65p
  labels:
    all_ages: All ages
    age_0_24: 0 to 24
    age_25_64: 25 to 64
    age_65p: 65+
  formatted:
    all_ages: all age groups
    age_0_24: 0 to 24 years old
    age_25_64: 25 to 64 years old
    age_65p: 65+ years old
  selected:
  - yes
  - no
  - no
  - no
outcomes:
  heading: Outcome
  values:
  - tb_infection_per_mil
  - pct_ltbi
  - tb_incidence_per_mil
  - pct_mdrtb_in_incident_tb
  - tb_deaths_per_mil
  labels:
    tb_infection_per_mil: New TB infections
    pct_ltbi: LTBI prevalence
    tb_incidence_per_mil: TB incidence
    pct_mdrtb_in_incident_tb: MDR-TB in Incident TB cases
    tb_deaths_per_mil: TB-related deaths
  formatted:
    tb_infection_per_mil: |-
      New TB Infections
      (per million)
    pct_ltbi: |-
      LTBI Prevalence
      (percentage)
    tb_incidence_per_mil: |-
      Incident M. TB Infection
      (per million)
    pct_mdrtb_in_incident_tb: |-
      MDR-TB in Incident TB Cases
      (percentage)
    tb_deaths_per_mil: |-
      TB-Related Deaths
      (per million)
  descriptions:
    tb_infection_per_mil: Incident M. TB infections each year due to transmission
      within the US (includes reinfection of individuals with prior infection, excludes
      immigrants entering the US with established LTBI)
    pct_ltbi: Prevalence of latent M. TB infections at mid-point of year
    tb_incidence_per_mil: TB cases identified each year (includes TB cases identified
      after death)
    pct_mdrtb_in_incident_tb: Of all incident TB cases identified each year, fraction
      with MDR-TB
    tb_deaths_per_mil: Number of deaths attributable to TB each year
  selected:
  - yes
  - no
  - no
  - no
  - no
interventions:
  heading: Intervention scenarios
  values:
  - intervention_1
  - intervention_2
  - intervention_3
  - intervention_4
  - intervention_5
  labels:
    intervention_1: TLTBI for new immigrants
    intervention_2: Improved TLTBI in the US
    intervention_3: Better case detection
    intervention_4: Better TB treatment
    intervention_5: All improvements
  descriptions:
    intervention_1: Provision of LTBI testing and treatment for all new legal
      immigrants entering the US
    intervention_2: Intensification of the current LTBI targeted testing and
      treatment policy for high-risk populations, doubling treatment uptake within
      each risk group compared to current levels, and increasing the fraction cured
      among individuals initiating LTBI treatment, via a 3-month Isoniazid-Rifapentine
      drug regimen
    intervention_3: Improved detection of active TB cases, such that the duration
      of untreated active disease (time from TB incidence to the initiation of
      treatment) is reduced by 50%
    intervention_4: Improved treatment quality for active TB, such that treatment default,
      failure rates, and the fraction of individuals receiving an incorrect drug
      regimen are reduced by 50% from current levels
    intervention_5: The combination of all intervention scenarios described above
analyses:
  heading: Additional scenarios
  values:
  - scenario_1
  - scenario_2
  labels:
    scenario_1: No transmission within the US after 2016
    scenario_2: No LTBI among immigrants after 2016
  formatted: # the |- allows newlines
    scenario_1: |-
      No transmission within
      the US after 2016
    scenario_2: |-
      No LTBI among
      immigrants after 2016
  descriptions:
    scenario_1: From 2016 onwards, no individuals acquire M. TB infection from transmission within
      the United States. In this scenario the only source of new LTBI cases is from
      existing infection in new immigrants.
    scenario_2: From 2016 onwards, all individuals immigrating to the United States are free of
      M. TB infection, while maintaining the same total volume of immigration.
downloads:
  heading: Download
  labels:
  - PNG
  - PDF
  - PPTX
  - CSV
  - XLSX
