font: Helvetica-Narrow
colors:
  base_case: '#000004FF'
  intervention_1: '#1B0C42FF'
  intervention_2: '#4B0C6BFF'
  intervention_3: '#781C6DFF'
  intervention_4: '#A52C60FF'
  intervention_5: '#CF4446FF'
  scenario_1: '#ED6925FF'
  scenario_2: '#FB9A06FF'
shapes:
  base_case: 21
  intervention_1: 21
  intervention_2: 22
  intervention_3: 23
  intervention_4: 24
  intervention_5: 25
  scenario_1: 22
  scenario_2: 23
fills:
  - '#F5F5F5'
  - '#1B0C42FF'
  - '#4B0C6BFF'
  - '#781C6DFF'
  - '#A52C60FF'
  - '#CF4446FF'
  - '#F5F5F5'
  - '#F5F5F5'
linetypes:
  base_case: 'solid'
  intervention_1: 'dashed'
  intervention_2: 'dotted'
  intervention_3: 'dotdash'
  intervention_4: 'longdash'
  intervention_5: 'twodash'
  scenario_1: '4C88C488'
  scenario_2: '12345678'
labels:
  base_case: Base case
  intervention_1: TLTBI for new immigrants
  intervention_2: Improved TLTBI in the US
  intervention_3: Better case detection
  intervention_4: Better TB treatment
  intervention_5: All improvements
  scenario_1: |-
    No transmission within
    the US after 2016
  scenario_2: |-
    No LTBI among
    immigrants after 2016
region:
  year:
    - 2000.0
    - 2025.0
    - 2050.0
    - 2075.0
    - 2100.0
  right_bound:
  - 2012.0
  - 2037.0
  - 2062.0
  - 2087.0
  - 2112.0
  left_bound:
  - 1988.0
  - 2013.0
  - 2038.0
  - 2063.0
  - 2088.0
  top_bound:
  - .inf
  - .inf
  - .inf
  - .inf
  - .inf
  bottom_bound:
  - -.inf
  - -.inf
  - -.inf
  - -.inf
  - -.inf
